
resume_training: False

experiment:
  experiments_base_dir: /home/stefan/workspace/experiments
  project_name: RNAformer
  session_name: rnaformer_1
  experiment_name: ts0_conform_test-0002


trainer:
  num_nodes: 1
  check_val_every_n_epoch: null #1
  default_root_dir: /home/stefan/workspace/
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  accelerator: 'gpu'
  devices: 1
  gradient_clip_val: 0.1
  limit_train_batches: null
  limit_val_batches: null
  log_every_n_steps: 10
  max_epochs: null
  max_steps: 100000
  num_sanity_val_steps: 2
  precision: 16
  reload_dataloaders_every_n_epochs: 1
  replace_sampler_ddp: false
  resume_from_checkpoint: null
  track_grad_norm: -1
  val_check_interval: 100



train:
  seed: 1234
  neg_samples: False # 500  # calculates the softmax CE loss only over #neg_samples+1 words
  softmax_temp: False  # calculates the softmax with temperature

  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.001
    weight_decay: 0.1
    betas:
      - 0.9
      - 0.98
    eps: 1.0e-09
    adam_w_mode: true
    seed: 1234
    scheduler_mult_factor: null
  optimizer_param_grouping:
    bias_weight_decay: False
    normalization_weight_decay: False
  scheduler:
    num_warmup_steps: 200 #${eval:0.01 * ${trainer.max_steps}}
    num_training_steps: ${trainer.max_steps}
    decay_factor: 0.1
    schedule: "cosine" # "cosine" or "linear"
  loss_fn:
    inplace_backward: True  # to save memory



callbacks:
  learning_rate_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${experiment.experiments_base_dir}
    auto_insert_metric_name: False
    every_n_train_steps: 10000
    every_n_epochs: null
    save_top_k: 1
    monitor: "step"
    mode: "max"
    filename: "checkpoint-{epoch:02d}-{global_step}"
    save_last: True


logger:
  tensorboard:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: "tensorboard/"
    name: ""
    version: "tb"
    log_graph: False
    default_hp_metric: True
    prefix: ""


deepspeed:
  zero_optimization: True
  stage: 2
  contiguous_gradients: false
  allgather_bucket_size: 5e8
  reduce_bucket_size: 5e8
  overlap_comm: true
  zero_allow_untested_optimizer: true


RNAformer:
  precision: ${trainer.precision}
  seq_vocab_size: 0
  trg_vocab_size: 0
  max_len: 0

  model_dim: 256 # hidden dimension of transformer
  n_layers: 6  # number of transformer layers
  num_head: 4  # number of heads per layer

  ff_factor: 4  # hidden dim * ff_factor = size of feed-forward layer
  ff_kernel: 3

  cycling: 6

  resi_dropout: 0.1
  embed_dropout: 0.1

  rel_pos_enc: True  # relative position encoding
  head_bias: False
  ln_eps: 1e-5

  softmax_scale: True
  key_dim_scaler: True
  gating: False
  use_glu: False
  use_bias: true

  flash_attn: false

  initializer_range: 0.02
  zero_init: false  # init last layer per block before each residual connection




# so the rfam has
# df=pd.read_pickle('/home/stefan/repos/RNAformer/data/rnafold_rfam_dataset.plk')
rna_data:
  # dataframe_path: "/data/rna/spotrna1_conform_with_TS0.plk"
  # dataframe_path: "/home/stefan/repos/RNAformer/data/rnafold_rfam_dataset.plk"
  dataframe_path: "/home/stefan/repos/pig/yoda/rnaformer_rfam.plk"
  valid_sets:  [44, 28, 5, 92, 52, 64, 38, 33, 112, 23, 4, 83, 74, 103, 94, 13, 53, 100, 119, 41, 101, 122]
  test_sets:  [7, 118, 60, 67, 91, 27, 3, 16, 59, 19, 113, 87, 104, 114, 120, 46, 43, 42, 80, 40, 48, 111]
  train_families: [110, 58, 32, 21, 2, 49, 50, 125, 51, 109, 22, 123, 89, 6, 85, 68, 95, 96, 75, 35, 98, 47, 69, 84, 57, 18, 39, 124, 77, 102, 62, 55, 117, 54, 90, 31, 11, 14, 105, 63, 36, 78, 81, 73, 97, 8, 26, 93, 12, 82, 34, 70, 99, 65, 1, 66, 115, 76, 20, 37, 45, 126, 30, 121, 17, 10, 71, 106, 108, 24, 116, 25, 29, 79, 61, 88, 72, 56, 9, 15]
  oversample_pdb: 1
  predict_canonical: false
  random_ignore_mat: 0.5
  partial_training: false
  design: False
  num_cpu_worker: 10
  num_gpu_worker: ${trainer.devices}
  min_len: 2
  max_len: 500
  similarity: 80 # never used in the code
  seed: 1
  batch_size: 2
  batch_by_token_size: false
  batch_token_size: 400
  shuffle_pool_size: 20
  cache_dir: "/tmp/data/cache"

  # defaultdict(list,
  #           {1: ['mir-19', 'mir-363'],
  #            2: ['SNORD88', 'snR76', 'snoR118'],
  #            3: ['snosnR60_Z15', 'SNORD77', 'Afu_263'],
  #            4: ['snoR30', 'SNORD100'],
  #            5: ['SNORD96', 'SNORD2'],
  #            6: ['SNORD105', 'snoU105B'],
  #            7: ['SNORD101', 'snoR60'],
  #            8: ['SNORND104', 'snR58'],
  #            9: ['SNORD110', 'snoR14'],
  #            10: ['snR68', 'snoR27'],
  #            11: ['SNORA73', 'snR30'],
  #            12: ['SNORD62', 'snoR41', 'snR41'],
  #            13: ['SNORD79',
  #             'SNORD113',
  #             'SNORD74',
  #             'snoR44_J54',
  #             'snosnR64',
  #             'snoMe28S-Cm2645',
  #             'SNORD64',
  #             'SNORD112',
  #             'SNORD109A'],
  #            14: ['SNORD60', 'snoR1', 'snosnR48', 'snoMe28S-G3255', 'sn2903'],
  #            15: ['SNORD61', 'snoU61', 'SNORD125'],
  #            16: ['SNORD58', 'SNORD99'],
  #            17: ['snoZ159', 'SNORD59', 'snosnR54'],
  #            18: ['SNORD49', 'snoZ112', 'snoU49'],
  #            19: ['SNORD52', 'SNORD53_SNORD92', 'snoZ157', 'snR78'],
  #            20: ['SNORD44', 'snoZ102_R77'],
  #            21: ['SNORD46', 'snR63'],
  #            22: ['mir-183', 'mir-182', 'mir-263', 'mir-228'],
  #            23: ['mir-137', 'mir-234'],
  #            24: ['bantam', 'mir-81'],
  #            25: ['mir-74', 'mir-73'],
  #            26: ['mir-BART1', 'mir-BART3'],
  #            27: ['mir-515', 'mir-290', 'mir-302', 'miR-430'],
  #            28: ['mir-279', 'mir-996'],
  #            29: ['mir-216', 'mir-283'],
  #            30: ['MIR171_1', 'MIR171_2'],
  #            31: ['MIR169_2', 'MIR169_5'],
  #            32: ['SCARNA4', 'SCARNA15'],
  #            33: ['SCARNA24', 'SCARNA3'],
  #            34: ['7SK', 'Arthropod_7SK'],
  #            35: ['SAM', 'SAM-IV', 'SAM-I-IV-variant'],
  #            36: ['GlmZ_SraJ', 'GlmY_tke1'],
  #            37: ['Hammerhead_3',
  #             'Hammerhead_1',
  #             'Hammerhead_HH9',
  #             'Hammerhead_II',
  #             'Hammerhead_HH10'],
  #            38: ['IRES_HCV', 'IRES_Pesti'],
  #            39: ['FinP', 'traJ_5'],
  #            40: ['CRISPR-DR5', 'CRISPR-DR7', 'CRISPR-DR63', 'CRISPR-DR64'],
  #            41: ['CRISPR-DR2',
  #             'CRISPR-DR4',
  #             'CRISPR-DR14',
  #             'CRISPR-DR17',
  #             'CRISPR-DR25',
  #             'CRISPR-DR43',
  #             'CRISPR-DR66'],
  #            42: ['snoR53', 'snoR53Y'],
  #            43: ['snoZ279_R105_R108', 'snoU13'],
  #            44: ['snoU89', 'snoU85'],
  #            45: ['mir-6', 'mir-11'],
  #            46: ['mir-3', 'mir-318'],
  #            47: ['mir-16', 'mir-15'],
  #            48: ['mir-28', 'mir-708'],
  #            49: ['mir-34', 'mir-449'],
  #            50: ['mir-36', 'mir-42', 'mir-35'],
  #            51: ['mir-190', 'mir-50'],
  #            52: ['L31-Coriobacteria',
  #             'L31-Corynebacteriaceae',
  #             'L31-Firmicutes',
  #             'L31-Gammaproteobacteria',
  #             'L31-Actinobacteria'],
  #            53: ['U54', 'snoU54'],
  #            54: ['U6', 'U6atac'],
  #            55: ['Glycine', 'glycine-GGAnGA'],
  #            56: ['TD-1', 'TD-2'],
  #            57: ['Purine', 'MFR', '2dG-II'],
  #            58: ['NiCo', 'NiCo-AnGGAG'],
  #            59: ['S15',
  #             'S15-Methanomicrobia',
  #             'S15-Halobacteria',
  #             'S15-Flavobacteria'],
  #            60: ['Twister-P5', 'twister-P3', 'twister-P1'],
  #            61: ['tRNA',
  #             'tmRNA',
  #             'alpha_tmRNA',
  #             'beta_tmRNA',
  #             'cyano_tmRNA',
  #             'tRNA-Sec',
  #             'mt-tmRNA'],
  #            62: ['RNaseP_nuc',
  #             'RNaseP_bact_a',
  #             'RNaseP_bact_b',
  #             'RNase_MRP',
  #             'RNaseP_arch',
  #             'RNase_P',
  #             'RNaseP-T'],
  #            63: ['Metazoa_SRP',
  #             'Bacteria_small_SRP',
  #             'Fungi_SRP',
  #             'Dictyostelium_SRP',
  #             'Bacteria_large_SRP',
  #             'Plant_SRP',
  #             'Protozoa_SRP',
  #             'Archaea_SRP',
  #             'Bacteroidales_small_SRP'],
  #            64: ['U1', 'U1_yeast', 'U11', 'Gl_U1'],
  #            65: ['U2', 'U12'],
  #            66: ['U4', 'U4atac'],
  #            67: ['SNORA36', 'snR36', 'snR44', 'S_pombe_snR36'],
  #            68: ['SNORA50', 'SNORA54', 'SNORA35', 'SNORA76'],
  #            69: ['SNORA48', 'snR86'],
  #            70: ['SNORA44', 'SNORA58', 'snR161', 'snR9'],
  #            71: ['SNORA21', 'snR10', 'S_pombe_snR10'],
  #            72: ['SNORA20', 'SNORA29'],
  #            73: ['SNORA28', 'snopsi18S-841', 'snR80'],
  #            74: ['SNORA27', 'SNORA26', 'snR42', 'S_pombe_snR42'],
  #            75: ['SNORA56', 'snR8'],
  #            76: ['SNORA66',
  #             'snoR98',
  #             'SNORA52',
  #             'SNORA18',
  #             'snoR80',
  #             'snR49',
  #             'snR5',
  #             'S_pombe_snR5'],
  #            77: ['Flavi_ISFV_repeat_Ra_Rb',
  #             'Flavi_ISFV_repeat_Rb',
  #             'Flavi_ISFV_repeat_Ra'],
  #            78: ['snoR9', 'snoPyro_CD', 'sR47', 'sR60'],
  #            79: ['c-di-GMP-II', 'c-di-GMP-II-GAG'],
  #            80: ['c-di-GMP-I', 'c-di-GMP-I-GGC', 'c-di-GMP-I-UAU'],
  #            81: ['SNORA3', 'snR11'],
  #            82: ['SNORA4', 'snR83'],
  #            83: ['SL1', 'SL2'],
  #            84: ['SNORA16',
  #             'SNORA2',
  #             'snopsi28S-3327',
  #             'snR189',
  #             'snR46',
  #             'S_pombe_snR46'],
  #            85: ['SNORA8', 'snR31'],
  #            86: ['SNORA9', 'snR33', 'snR43', 'S_pombe_snR33'],
  #            87: ['SNORA5', 'snR85'],
  #            88: ['SNORA7', 'snR81'],
  #            89: ['SNORA13', 'snR35', 'S_pombe_snR35'],
  #            90: ['SNORA43', 'SNORA17'],
  #            91: ['Cobalamin', 'AdoCbl_riboswitch', 'AdoCbl-variant'],
  #            92: ['U3', 'Fungi_U3', 'Plant_U3', 'ACEA_U3'],
  #            93: ['SNORD11', 'SNORD11B'],
  #            94: ['group-II-D1D4-1',
  #             'group-II-D1D4-2',
  #             'group-II-D1D4-3',
  #             'group-II-D1D4-4',
  #             'group-II-D1D4-5',
  #             'group-II-D1D4-6',
  #             'group-II-D1D4-7'],
  #            95: ['SraC_RyeA', 'SdsR_RyeB'],
  #            96: ['HBV_epsilon', 'AHBV_epsilon'],
  #            97: ['CsrB',
  #             'CsrC',
  #             'McaS',
  #             'PrrB_RsmZ',
  #             'RsmY',
  #             'TwoAYGGAY',
  #             'rsmX',
  #             'Ysr186_sR026_CsrC',
  #             'RsmW'],
  #            98: ['suhB', 'ar15'],
  #            99: ['cHP', 'DENV_SLA', 'Flavivirus-5UTR'],
  #            100: ['C4', 'c4-2', 'c4-a1b1'],
  #            101: ['SNORD39',
  #             'snoZ7',
  #             'snoZ101',
  #             'SNORD65',
  #             'snoR77Y',
  #             'snR77'],
  #            102: ['SNORD35', 'snoZ161_228', 'snR73'],
  #            103: ['SNORD34', 'snR62'],
  #            104: ['SNORD33',
  #             'snoZ196',
  #             'SNORD51',
  #             'snosnR55',
  #             'snoMe18S-Um1356',
  #             'snoMe28S-Am982',
  #             'snR39',
  #             'snR40'],
  #            105: ['SNORD31', 'snoZ17', 'snR67', 'snoR35'],
  #            106: ['SNORD30', 'snoU30'],
  #            107: ['SNORD36',
  #             'SNORD29',
  #             'snoZ223',
  #             'SNORD38',
  #             'snosnR69',
  #             'snosnR61',
  #             'snosnR71',
  #             'SNORD78',
  #             'snoR69Y',
  #             'snR47',
  #             'snoU36a'],
  #            108: ['SNORD26', 'SNORD81'],
  #            109: ['aCoV-5UTR',
  #             'bCoV-5UTR',
  #             'gCoV-5UTR',
  #             'dCoV-5UTR',
  #             'Sarbecovirus-5UTR'],
  #            110: ['s2m',
  #             'Corona_pk3',
  #             'aCoV-3UTR',
  #             'bCoV-3UTR',
  #             'gCoV-3UTR',
  #             'dCoV-3UTR',
  #             'Sarbecovirus-3UTR'],
  #            111: ['LhrC', 'rli22', 'rli33'],
  #            112: ['DUF805b', 'DUF805'],
  #            113: ['5S_rRNA', 'mtPerm-5S'],
  #            114: ['SNORD43', 'snR70'],
  #            115: ['SNORD57', 'SNORD41', 'snR51'],
  #            116: ['SNORD12', 'snR190'],
  #            117: ['SNORD15', 'snR75', 'snR13', 'snoZ5'],
  #            118: ['SNORD16', 'snR87'],
  #            119: ['SNORD18', 'snoU18'],
  #            120: ['SNORA62', 'snR3', 'snR82', 'S_pombe_snR3'],
  #            121: ['SNORA64', 'snR37'],
  #            122: ['SNORA65', 'snR34', 'snoR2'],
  #            123: ['SNORA74', 'snR191'],
  #            124: ['S4-Fusobacteriales',
  #             'S4-Bacteroidia',
  #             'S4-Clostridia',
  #             'S4-Flavobacteria'],
  #            125: ['SNORD19', 'SNORD19B'],
  #            126: ['SNORD25', 'snR56f']})
